### ISSUE TITLE
Error: remoteAddress not set

### ISSUE THREAD

**Issue by tushar-novopay** [kpavlov/jreactive-8583#33]
Our server is running fine and below is very basic version of our code:

                MessageFactory<IsoMessage> messageFactory = ConfigParser.createDefault();
		Iso8583Client<IsoMessage> client = new Iso8583Client< (socketAddress,ClientConfiguration.getDefault(),messageFactory);
		client.addMessageListener(new IsoMessageListener<IsoMessage>() {

		        @Override
			public boolean applies(IsoMessage arg0) {

				return false;
			}

			@Override
			public boolean onMessage(ChannelHandlerContext arg0, IsoMessage arg1) {

				return false;
			}
		});
		client.getConfiguration().setReplyOnError(true);
		
		client.init();
		EventLoopGroup group = new NioEventLoopGroup();
		try {
			client.connect("127.0.0.1", 8080);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			System.out.println("Problem in client Connection");
			e.printStackTrace();
		}

I am getting following error, please help:
**Exception in thread "main" java.lang.IllegalStateException: remoteAddress not set
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
	at com.github.kpavlov.jreactive8583.client.Iso8583Client.connectAsync(Iso8583Client.java:88)
	at com.github.kpavlov.jreactive8583.client.Iso8583Client.connect(Iso8583Client.java:48)
	at com.github.kpavlov.jreactive8583.client.Iso8583Client.connect(Iso8583Client.java:75)
	at com.github.kpavlov.jreactive8583.client.Iso8583Client.connect(Iso8583Client.java:63)
	at com.tushar.jreactive8583.demo_iso8385.AppClient.main(AppClient.java:62)**

**Comment by tushar-novopay** [comment]
Issue resolved!! Thanks

**Comment by kiakaku** [comment]
Please give me solution

**Comment by kpavlov** [comment]
Check [Iso8583ServerConfig](https://github.com/kpavlov/jreactive-8583/blob/master/src/test/java/com/github/kpavlov/jreactive8583/example/server/Iso8583ServerConfig.java)
